/**
 * Learn + stake-flow copy deck entry (P1-13).
 * Stake-specific strings live in `client/src/staking/copy.ts` and are re-exported
 * here so Learn articles and polish passes share one import surface.
 */

export {
  OPERATION_LABELS,
  STAKE_AMOUNT_LEDE,
  STAKE_AMOUNT_TITLE,
  STAKE_BACK_HOME,
  STAKE_CANCEL,
  STAKE_CANCELLED,
  STAKE_CONFIRM_CTA,
  STAKE_CONFIRM_TIMEOUT,
  STAKE_CONNECT_FIRST,
  STAKE_CONTINUE_REVIEW,
  STAKE_DONE,
  STAKE_FEE_HEADROOM_NOTE,
  STAKE_IN_PROGRESS,
  STAKE_INTENT_GONE,
  STAKE_MAINNET_REAL_AMOUNTS,
  STAKE_NO_ILLUSTRATIVE_ON_REVIEW,
  STAKE_NON_CUSTODIAL,
  STAKE_NO_WAITING_PERIOD,
  STAKE_OTHER_VALIDATOR,
  STAKE_PENDING_BODY,
  STAKE_PENDING_TITLE,
  STAKE_PRESET_25,
  STAKE_PRESET_50,
  STAKE_PRESET_CUSTOM,
  STAKE_PRESET_MAX,
  STAKE_PROVIDER_ERROR,
  STAKE_REVIEW_BEFORE_CONFIRM,
  STAKE_REVIEW_TITLE,
  STAKE_SUCCESS_BODY,
  STAKE_SUCCESS_TITLE,
  STAKE_TX_FAILED,
  STAKE_TX_MISMATCH,
  formatStateTransition,
} from '../staking/copy'
